kumuluzee:
  env: dev

  fault-tolerance:
    bulkhead:
      value: 5

    annotation-overrides:
      - class: com.kumuluz.ee.samples.circuit_breaker_hystrix.customer.beans.OrdersBean
        method: findOrdersByCustomerId
        annotation: timeout
        parameters:
          value: 1500
      - class: com.kumuluz.ee.samples.circuit_breaker_hystrix.customer.beans.OrdersBean
        method: findOrdersByCustomerId
        annotation: circuit-breaker
        parameters:
          request-threshold: 10
          failure-ratio: 0.3
          delay: 3000

orders-api:
  path: http://localhost:8081/v1/orders
