kumuluzee:
  server:
    http:
      port: 8081

  rest-client:
    propagate-headers: Authorization
    registrations:
      - class: com.kumuluz.ee.samples.kumuluzee_rest_client.api.CustomerApi
        url: http://localhost:8080/v1
