kumuluzee:
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:postgresql://192.168.144.129:5432/customers
      username: postgres
      password: cG9zdGdyZXM=
      pool:
        max-size: 20