kumuluzee:
  name: "grpc-server"
  server:
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/UsersDB
      connection-url: jdbc:postgresql://192.168.99.100:5432/users
      username: postgres
      password: postgres
  grpc:
    server:
      http:
        port: 8081
      auth:
        public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDW6Angsf0Ry+GFD5HPstdcuaHJU5KhpT+gkzCCx7zZAbKRaEQexaTA9nPXK2Uzk2JqWTbZXSQYX2kBzYeiiedMpW6wvTaZWL9QhGjEnA9o97oNV1G5wQHKL/8FsvLXqt/81BCeZzWPDGvLNuU9l0qK3/xXL3efaZYPsZkB2AyZiQIDAQAB
        issuer: http://localhost